import { Studio } from "./studio.component";

// Set the right `viewport`, `robots` and `referer` meta tags
import { metadata as _meta } from "next-sanity/studio/metadata";

export const metadata = {
  ..._meta,
  viewport: "width=device-width",
  title: "Meow Meow Collectibles",
  description: "Generated by create next app",
  icons: [
    {
      rel: "apple-touch-icon",
      sizes: "180x180",
      url: "/apple-touch-icon.png",
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "32x32",
      url: "/favicon-32x32.png",
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "16x16",
      url: "/favicon-16x16.png",
    },
    {
      rel: "mask-icon",
      url: "/safari-pinned-tab.svg",
    },
  ],
  manifest: "/site.webmanifest",
  themeColor: "#ffffff",
};

export default function StudioPage() {
  return (
    <>
      <Studio />
    </>
  );
}
